#!/bin/bash

# Copyright (C) OQS-MOFF.


# Retrieve current NGINX config arguments, append arguments for redirect openssl to OQS openssl

echo 'Retrieving current NGINX configuration arguments...'

#cmdArgs=()

#declare -a cmdArgs='([0]="date")'
declare -a cmdArgs='([0]="nginx -V  2>&1 | grep \'configure arguments:\' | awk \'{print \$2}\' FS=\'configure arguments:\'")'

"${cmdArgs[0]}"

#declare -p cmdArgs #See content of the array inside with each command parameter in seperate indices. 
